farzone/farzone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
    path('users/', include('users.urls', namespace='users')),
]

# Обслуживание статических и медиафайлов
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farzone/forum/urls.py
from django.urls import path
from .views import (
    ForumHomeView,
    CategoryPostsView,
    PostDetailView,
    PostCreateView,
    CommentCreateView,
    WelcomeView,
    PostListCreateAPIView,
    CategoryListAPIView,
    PostLikeView,
)

urlpatterns = [
    path('', WelcomeView.as_view(), name='welcome'),
    path('forum/', ForumHomeView.as_view(), name='forum_home'),
    path('category/<slug:slug>/', CategoryPostsView.as_view(), name='category_posts'),
    path('category/<slug:slug>/new/', PostCreateView.as_view(), name='post_create'),
    path('category/<slug:category_slug>/<slug:post_slug>/', PostDetailView.as_view(), name='post_detail'),
    path('category/<slug:category_slug>/<slug:post_slug>/comment/', CommentCreateView.as_view(), name='add_comment'),
    path('category/<slug:category_slug>/<slug:post_slug>/like/', PostLikeView.as_view(), name='post_like'),
    path('api/posts/', PostListCreateAPIView.as_view(), name='post_list_create_api'),
    path('api/categories/', CategoryListAPIView.as_view(), name='category_list_api'),
]

farzone/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.decorators.http import require_http_methods

from .views import RegisterView, ProfileView, ProfileEditView, PublicProfileView, AuthAPIView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileEditView.as_view(), name='profile_edit'),
    path('profile/<str:username>/', PublicProfileView.as_view(), name='profile_view'),
    path('api/auth/', AuthAPIView.as_view(), name='api_auth'),
]

farzone/forum/forms.py
from django import forms
from .models import Post, Comment, ContactMessage


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'class': 'form-textarea'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.user:
            instance.author = self.user
        if commit:
            instance.save()
        return instance


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'form-textarea',
                'rows': 3,
                'placeholder': 'Оставьте ваш комментарий...'
            }),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        comment = super().save(commit=False)
        if self.user:
            comment.author = self.user
        if commit:
            comment.save()
        return comment


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'message']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-input',
                'placeholder': 'Ваше имя'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-input',
                'placeholder': 'Ваш email'
            }),
            'message': forms.Textarea(attrs={
                'class': 'form-textarea',
                'rows': 4,
                'placeholder': 'Ваше сообщение'
            }),
        }

farzone/forum/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from django.shortcuts import get_object_or_404, redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from .forms import CommentForm, PostForm, ContactForm
from .models import Category, Post, Comment, PostLike, ContactMessage
from django.conf import settings
from .serializers import PostSerializer, CategorySerializer
from rest_framework import generics
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from django.views import View
import logging
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

logger = logging.getLogger(__name__)

class WelcomeView(TemplateView):
    template_name = 'forum/welcome.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['yandex_maps_api_key'] = settings.YANDEX_MAPS_API_KEY
        context['form'] = ContactForm()
        context['form_success'] = self.request.session.pop('form_success', False)
        return context

    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['form_success'] = True
            return redirect('welcome')
        context = self.get_context_data(**kwargs)
        context['form'] = form
        return self.render_to_response(context)

class CategoryListAPIView(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

class PostListCreateAPIView(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

class ForumHomeView(ListView):
    model = Category
    template_name = 'forum/index.html'
    context_object_name = 'categories'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Форум по настольному теннису'
        first_category = self.object_list.first()
        context['active_category'] = first_category
        if first_category:
            posts = first_category.posts.all()
            if self.request.user.is_authenticated:
                liked_post_ids = set(PostLike.objects.filter(
                    post__in=posts, user=self.request.user
                ).values_list('post_id', flat=True))
                context['posts'] = [
                    {
                        'post': post,
                        'user_liked': post.id in liked_post_ids,
                        'likes_count': post.likes.count()
                    }
                    for post in posts
                ]
            else:
                context['posts'] = [
                    {
                        'post': post,
                        'user_liked': False,
                        'likes_count': post.likes.count()
                    }
                    for post in posts
                ]
        else:
            context['posts'] = []
        return context

class CategoryPostsView(ListView):
    model = Post
    template_name = 'forum/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return self.category.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Форум - {self.category.title}'
        context['categories'] = Category.objects.all()
        context['active_category'] = self.category
        posts = self.get_queryset()
        if self.request.user.is_authenticated:
            liked_post_ids = set(PostLike.objects.filter(
                post__in=posts, user=self.request.user
            ).values_list('post_id', flat=True))
            context['posts'] = [
                {
                    'post': post,
                    'user_liked': post.id in liked_post_ids,
                    'likes_count': post.likes.count()
                }
                for post in posts
            ]
        else:
            context['posts'] = [
                {
                    'post': post,
                    'user_liked': False,
                    'likes_count': post.likes.count()
                }
                for post in posts
            ]
        return context

class PostDetailView(DetailView):
    model = Post
    template_name = 'forum/post-detail.html'
    context_object_name = 'post'
    slug_url_kwarg = 'post_slug'

    def get_object(self, queryset=None):
        category_slug = self.kwargs.get('category_slug')
        post_slug = self.kwargs.get('post_slug')
        return get_object_or_404(
            Post,
            category__slug=category_slug,
            slug=post_slug
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        context['categories'] = Category.objects.all()
        context['active_category'] = self.object.category
        comments = self.object.comments.filter(is_published=True)
        context['comments'] = [
            {'comment': comment} for comment in comments
        ]
        context['comment_form'] = CommentForm()
        if self.request.user.is_authenticated:
            context['user_liked_post'] = PostLike.objects.filter(post=self.object, user=self.request.user).exists()
        context['post_likes_count'] = self.object.likes.count()
        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'forum/post-create.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('post_detail', kwargs={
            'category_slug': self.object.category.slug,
            'post_slug': self.object.slug
        })

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    login_url = '/users/login/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.post = get_object_or_404(
            Post,
            category__slug=self.kwargs['category_slug'],
            slug=self.kwargs['post_slug']
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('post_detail', kwargs={
            'category_slug': self.kwargs['category_slug'],
            'post_slug': self.kwargs['post_slug']
        }) + '#comments'

@method_decorator(csrf_exempt, name='dispatch')
class PostLikeView(LoginRequiredMixin, View):
    def post(self, request, category_slug, post_slug):
        logger.info(f"Received like request for category_slug={category_slug}, post_slug={post_slug}, user={request.user.username}")
        if not request.user.is_authenticated:
            logger.warning("Unauthenticated user attempted to like post")
            return JsonResponse({'status': 'error', 'message': 'Authentication required'}, status=401)

        post = get_object_or_404(Post, category__slug=category_slug, slug=post_slug)
        try:
            liked = PostLike.objects.filter(post=post, user=request.user).exists()
            action = 'unliked' if liked else 'liked'

            if liked:
                PostLike.objects.filter(post=post, user=request.user).delete()
            else:
                PostLike.objects.create(post=post, user=request.user)

            likes_count = post.likes.count()
            logger.info(f"User {request.user.username} {action} post {post.id}, likes count: {likes_count}")

            # Attempt WebSocket update, but don't fail the request
            try:
                channel_layer = get_channel_layer()
                if channel_layer:
                    async_to_sync(channel_layer.group_send)(
                        f'post_{post.id}',
                        {
                            'type': 'like_update',
                            'post_id': post.id,
                            'likes_count': likes_count,
                            'action': action,
                            'user_id': request.user.id
                        }
                    )
                    logger.info(f"Sent WebSocket update for post {post.id}")
                else:
                    logger.warning("Channel layer not initialized, skipping WebSocket update")
            except Exception as e:
                logger.error(f"Failed to send WebSocket update for post {post.id}: {str(e)}")

            return JsonResponse({
                'status': 'success',
                'action': action,
                'likes_count': likes_count
            })
        except Exception as e:
            logger.error(f"Error processing like for post {post.id} by user {request.user.username}: {str(e)}")
            return JsonResponse({'status': 'error', 'message': 'Internal server error'}, status=500)

farzone/forum/templates/forum/index.html
{% extends 'base.html' %}
{% load static %}
{% load forum_tags %}

{% block content %}
<div class="forum-main">
    <div class="categories-sidebar">
        <ul class="categories-list">
            {% for category in categories %}
            <li class="category-item {% if category == active_category %}active{% endif %}">
                <a href="{{ category.get_absolute_url }}" class="category-link">{{ category.title }}</a>
            </li>
            {% empty %}
            <li class="category-item">No categories available</li>
            {% endfor %}
        </ul>
    </div>

    <div class="posts-main">
        <div class="posts-header">
            <h2 class="category-title">{{ active_category.title|default:"No Category Selected" }}</h2>
            {% if user.is_authenticated and active_category %}
            <button class="add-button">
                <a href="{% url 'post_create' slug=active_category.slug %}">+</a>
            </button>
            {% elif active_category %}
            <button class="add-button">
                <a href="{% url 'users:login' %}?next={% url 'post_create' slug=active_category.slug %}">+</a>
            </button>
            {% endif %}
        </div>

        <ul class="posts-list">
            {% for post_data in posts %}
            {% if post_data.post.is_published %}
            <li>
                <div class="post-card">
                    <div class="post-title">
                        <a href="{{ post_data.post.get_absolute_url }}">{{ post_data.post.title }}</a>
                    </div>

                    <div class="post-meta">
                        <span class="post-author">
                            <a href="{% url 'users:profile_view' username=post_data.post.author.username %}">
                                <i class="bi bi-person-circle profile-icon"></i>
                            </a>
                        </span>

                        <span class="post-username">{{ post_data.post.author.username }}</span>

                        <span class="post-date">
                            <i class="bi bi-clock"></i>
                            {{ post_data.post.created_at|date:"d.m.Y H:i" }}
                        </span>

                        <span class="post-likes">
                            <i class="bi {% if post_data.user_liked %}bi-heart-fill{% else %}bi-heart{% endif %} like-icon"
                               data-post-id="{{ post_data.post.id }}"
                               data-post-slug="{{ post_data.post.slug }}"
                               data-category-slug="{{ post_data.post.category.slug }}"
                               data-liked="{% if post_data.user_liked %}true{% else %}false{% endif %}"></i>
                            <span class="likes-count" data-post-id="{{ post_data.post.id }}">{{ post_data.likes_count }}</span>
                        </span>
                    </div>

                    <div class="post-content">
                        <p>{{ post_data.post.content|truncate_chars:75 }}</p>
                    </div>
                </div>
            </li>
            {% endif %}
            {% empty %}
            <li>No posts available</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'forum/js/script.js' %}"></script>
<script src="{% static 'forum/js/likes.js' %}"></script>
{% endblock %}

farzone/forum/templates/forum/post-create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="post-create-container">
    <div class="post-create">
        <h1>Создать новый пост</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.title.label_tag }}
                {{ form.title }}
            </div>
            <div class="form-group">
                {{ form.category.label_tag }}
                {{ form.category }}
            </div>
            <div class="form-group">
                {{ form.content.label_tag }}
                {{ form.content }}
            </div>
            <button type="submit" class="submit-button">Опубликовать</button>
        </form>
    </div>
</div>
{% endblock %}

farzone/forum/templates/forum/post-detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="forum-main">
    <div class="categories-sidebar">
        <ul class="categories-list">
            {% for category in categories %}
            <li class="category-item {% if category == active_category %}active{% endif %}">
                <a href="{{ category.get_absolute_url }}" class="category-link">{{ category.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div class="posts-main">
        <div class="post-detail" data-post-id="{{ post.id }}" data-user-id="{{ user.id|default:0 }}">
            <div class="post-header">
                <h1 class="post-title">{{ post.title }}</h1>
                <div class="post-meta">
                    <span class="post-author">
                        <a href="{% url 'users:profile_view' username=post.author.username %}">
                            <i class="bi bi-person-circle profile-icon"></i>
                        </a>
                    </span>

                    <span class="post-username">{{ post.author.username }}</span>

                    <span class="post-date">
                        <i class="bi bi-clock"></i>
                        {{ post.created_at|date:"d.m.Y H:i" }}
                    </span>

                    <span class="post-likes">
                        <i class="bi {% if user_liked_post %}bi-heart-fill{% else %}bi-heart{% endif %} like-icon"
                           data-post-id="{{ post.id }}"
                           data-post-slug="{{ post.slug }}"
                           data-category-slug="{{ post.category.slug }}"
                           data-liked="{% if user_liked_post %}true{% else %}false{% endif %}"></i>
                        <span class="likes-count" data-post-id="{{ post.id }}">{{ post_likes_count }}</span>
                    </span>
                </div>
            </div>

            <div class="post-content">
                <p>{{ post.content|linebreaks }}</p>
            </div>
        </div>

        <div class="comments-section" id="comments">
            <h2 class="comments-title">Комментарии</h2>

            <div class="comment-form" id="comment-form">
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'add_comment' category_slug=post.category.slug post_slug=post.slug %}">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    <button type="submit" class="comment-submit">Отправить</button>
                </form>
                {% else %}
                <div class="auth-required">
                    <p>Чтобы оставить комментарий, пожалуйста <a href="{% url 'users:login' %}?next={% url 'post_detail' category_slug=post.category.slug post_slug=post.slug %}#comment-form">войдите</a> или <a href="{% url 'users:register' %}">зарегистрируйтесь</a></p>
                </div>
                {% endif %}
            </div>

            <ul class="comments-list">
                {% for comment_data in comments %}
                <li class="comment">
                    <div class="comment-header">
                        <span class="comment-author">
                            {% if comment_data.comment.author and comment_data.comment.author.username %}
                            <a href="{% url 'users:profile_view' username=comment_data.comment.author.username %}">
                                <i class="bi bi-person-circle profile-icon"></i>
                            </a>
                            {% else %}
                            <i class="bi bi-person-circle profile-icon"></i>
                            {% endif %}
                        </span>

                        <span class="comment-username">
                            {{ comment_data.comment.author.username|default:"Удаленный пользователь" }}
                        </span>

                        <span class="comment-date">
                            <i class="bi bi-clock"></i>
                            {{ comment_data.comment.created_at|date:"d.m.Y H:i" }}
                        </span>
                    </div>
                    <div class="comment-content">
                        {{ comment_data.comment.content|linebreaks }}
                    </div>
                </li>
                {% empty %}
                <li class="no-comments">Пока нет комментариев. Будьте первым!</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'forum/js/script.js' %}"></script>
<script src="{% static 'forum/js/likes.js' %}"></script>
<script src="{% static 'forum/js/post_websocket.js' %}"></script>
{% endblock %}

farzone/forum/templates/forum/welcome.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="welcome-container">
    <!-- Видео на фоне -->
    <div class="video-section">
        <video autoplay muted loop playsinline preload="metadata" class="background-video">
            <source src="{% static 'forum/videos/video.webm' %}" type="video/webm">
            <source src="{% static 'forum/videos/video.mp4' %}" type="video/mp4">
            Ваш браузер не поддерживает видео.
        </video>
        <div class="video-overlay">
            <h1 class="welcome-title">Добро пожаловать на форум по настольному теннису!</h1>
            <h2 class="welcome-title">Станьте частью сообщества прямо сейчас</h2>
            <a href="{% url 'forum_home' %}" class="forward-button">Вперёд</a>
        </div>
    </div>

    <!-- Секция О нас -->
    <div class="about-section">
        <h2>О нас</h2>
        <p>
            Форум был создан в качестве учебного проекта человеком, которому не безразличен данный вид спорта.
            Наша задача была сделать максимально дружелюбный и уютный ресурс, на котором каждый любитель настольного
            тенниса мог найти единомышленников. Делитесь своими успехами, обсуждайте инвентарь, спрашивайте советы у
            опытных игроков, а самое главное - просто получайте удовольствие на нашем сайте!
        </p>
    </div>

    <!-- Секция Контакты и карта -->
    <div class="contact-section">
        <h2>Контакты</h2>
        <p><strong>Адрес:</strong> г. Москва, г. Зеленоград, ул. Юности, д.15</p>
        <p><strong>Email:</strong> <a href="mailto:dmitriyeltanskiy48@yandex.ru">dmitriyeltanskiy48@yandex.ru</a></p>
        <p><strong>Телефон:</strong> +7 (905) 682-98-73</p>

        <!-- Форма обратной связи -->
        <div class="contact-form">
            <h3>Обратная связь</h3>
            <form method="post" id="contact-form" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <span class="form-label">Имя</span>
                    {{ form.name }}
                    <div class="error-message" id="id_name-error"></div>
                </div>
                <div class="form-group">
                    <span class="form-label">Email</span>
                    {{ form.email }}
                    <div class="error-message" id="id_email-error"></div>
                </div>
                <div class="form-group">
                    <span class="form-label">Сообщение</span>
                    {{ form.message }}
                    <div class="error-message" id="id_message-error"></div>
                </div>
                <button type="submit" class="submit-button">Отправить</button>
            </form>
            {% if form_success %}
                <p class="success-message">Сообщение успешно отправлено!</p>
            {% endif %}
        </div>

        <div id="map" class="map-container"></div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'forum/js/script.js' %}"></script>
{% if yandex_maps_api_key %}
<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&apikey={{ yandex_maps_api_key }}" type="text/javascript"></script>
{% else %}
<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
{% endif %}
<script src="{% static 'forum/js/map.js' %}"></script>
{% endblock %}